name: FIXER
favicon: null
layout_spectrum: 0.6198246479034424
typography_spectrum: 0.46626626164652407
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8891178984194994
  lightness: 0.8605474757496268
  saturation: 0.6846744765061885
  rhythmicContrast: 0.6901713206898421
purpose: []
